hw2/config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'age', to: 'pages#age'
  post 'stringify', to: 'pages#stringify'
  put 'age', to: 'pages#person'
  get 'me', to: 'pages#me'
end

hw2/app/controllers/concerns/foobar.rb
class Foobar
  # ENTER CODE FOR Q2 HERE
  def initialize(param)
  	@param = param
  end

  def bar (*args)
  	args[0].to_s <<  @param << args[1][:sat].to_s
  end
end

hw2/app/controllers/concerns/person.rb
class Person
  attr_accessor :name, :age

  def initialize(name, age)
    @name = name
    @age = age
  end

  def nickname
      @name[/^\w{0,4}/]
  end

  def birth_year
     current_year = Date.today.year
     current_year - @age.to_i
  end

  def introduction
    @name.to_s << " " << @age.to_s
  end

  def fib_number
    memo = []
    (0..@age.to_i).each do |i|
      memo[i] = i < 2 ? i : memo[i-1] + memo[i-2]
    end
    memo[@age.to_i]
  end
end

hw2/app/controllers/concerns/stringify.rb
class Stringify
  attr_accessor :name, :adjective

  def initialize(name, adjective)
    @name = name
    @adjective = adjective
  end

  def what_am_i
    if @name.blank? || @adjective.blank?
      "You are nothing!"
    else
      @name << " is so " << @adjective
    end
  end
end

hw2/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    foo = Foobar.new "baz"
    @baz = foo.bar :cat, sat: :dat, dat: :sat
  end

  def stringify
    stringify_instance = Stringify.new(
      params[:name],
      params[:adjective]
    )
    @text = stringify_instance.what_am_i
  end

  def age
  end

  def person
    @person = Person.new params[:name], params[:age]
  end
  def me
  end
end

hw2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hw2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

hw2/app/views/pages/age.html.erb
<h1>REROUTE ME!</h1>

hw2/app/views/pages/home.html.erb
<h1>Hello There! Welcome to homework 2!</h1>
<p>What a beautiful homepage!</p>
<p>Good thing this isn't the web design decal.</p>

<h1>Question 1</h1>

<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<%= form_tag stringify_path do %>
  <%= label_tag :name, "Your Name here!" %>
  <%= text_area_tag :name %>
  <%= label_tag :adjective, "An adjective here!" %>
  <%= text_area_tag :adjective %>
  <%= submit_tag "Stringify!" %>
<% end %>
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->

<h1>Question 2</h1>

<p>Your result</p>
<%= @baz %>

<h1>Question 3</h1>

<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<%= form_tag age_path, method: :put do %>
  <%= label_tag :name, "Your name:" %>
  <%= text_area_tag :name %>
  <%= label_tag :age, "Your age:" %>
  <%= text_area_tag :age %>
  <%= submit_tag "Submit!" %>
<% end %>
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<!-- CONFUSING CODE, DO NOT MODIFY -->
<h1>Question 4</h1>
<%= link_to "My Profile", me_path%>

hw2/app/views/pages/me.html.erb
<body class="parag">
	<h1 id="name" > Muluken Taye </h1>

	<%= image_tag "mul.png", :size => '400x480' %>

	<h3> 
		<span class="origin"> I'm from Ethiopia</span>, senior, EECS major.<br>
		<span class="fun_fact"> I had little interest watching Basketball and I was into soccer. However, I have become a big Warriors fan in the last few years :) </span>
	</h3>
	
</body>

hw2/app/views/pages/person.html.erb
<h1>Name: </h1>
<%= @person.name %>
<br/>
<h1>Introduction: </h1>
<%= @person.introduction %>
<br/>
<h1>Nickname: </h1>
<%= @person.nickname %>
<br />
<h1>Birth year: </h1>
<%= @person.birth_year %>
<br />
<h1>Fib number</h1>
<%= @person.fib_number %>

hw2/app/views/pages/stringify.html.erb
<%= @text %>